name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies and build
      run: npm i
    - name: lint
      run: npm run lint
    - name: build
      run: npm run build
    - name: test
      run: npm run test
